BASE_URL = 'https://qa-scooter.praktikum-services.ru'
CREATE_COURIER_ENDPOINT = '/api/v1/courier'
COURIER_AUTH_ENDPOINT = '/api/v1/courier/login'
CREATE_ORDER_ENDPOINT = '/api/v1/orders'
CANCEL_ORDER_ENDPOINT = '/api/v1/orders/cancel'
LIST_ORDERS_ENDPOINT = '/api/v1/orders'
DELETE_COURIER_ENDPOINT = '/api/v1/courier'